Algoritmo "nota"

Var
    nota,media,number,numero:real


Inicio
        escreva("Digite sua nota")
        leia (nota)

        escreva("Digíte sua outra nota")
        leia (media)
        

         number <- nota + media
         
         numero <- number / 2
         
         escreva (numero)
         

        

        


        
        
        




Fimalgoritmo